version: "3.9"
services:
  jenkins:
      image: jenkins/jenkins:lts
      privileged: true
      user: root
      ports:
        - 8081:8080
        - 50000:50000
      container_name: jenkins
      volumes:
        - /jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - /usr/libexec/docker/cli-plugins:/usr/libexec/docker/cli-plugins
        - /usr/local/bin/com.docker.cli:/usr/local/bin/com.docker.cli
      networks:
        - jenkins
networks:
  jenkins:
    name: cluster2
